# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a5d114d597a26d4a17bf84275d7b309c86ce577f4d3b976ddf55c39630831f670fe82a968feda75d31157d5a7150fc8d9e64e46106b55a3cdb1b7073dae41de

test:
  secret_key_base: 41ac2c3235524834d35638a90078a7919f911e49bd8155396ef6d5bbdb99e77d1a6bfc8e68c93b06fe85e320c60157a268074de595a76b4dbeaa29ae99e2dc8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
